global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
      - auto_route_generator
  hive_generator:
    runs_before:
      - retrofit_generator
  
