// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLA5oXR27cXVDJeVVdQVnKxxObMxNdoCk',
    appId: '1:364300700938:web:8b539626613617fe9cbef3',
    messagingSenderId: '364300700938',
    projectId: 'fir-notifications-api',
    authDomain: 'fir-notifications-api.firebaseapp.com',
    storageBucket: 'fir-notifications-api.firebasestorage.app',
    measurementId: 'G-79XWQT83DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOhB50EAIIbtPcLSlns4CSjSlkiTqHiE',
    appId: '1:364300700938:android:9770be26e94f08349cbef3',
    messagingSenderId: '364300700938',
    projectId: 'fir-notifications-api',
    storageBucket: 'fir-notifications-api.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6hQ4H4Y1FRt9UVk025KZhYAGd1LaJG8',
    appId: '1:364300700938:ios:598217a9807f23869cbef3',
    messagingSenderId: '364300700938',
    projectId: 'fir-notifications-api',
    storageBucket: 'fir-notifications-api.firebasestorage.app',
    iosBundleId: 'com.example.carey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6hQ4H4Y1FRt9UVk025KZhYAGd1LaJG8',
    appId: '1:364300700938:ios:598217a9807f23869cbef3',
    messagingSenderId: '364300700938',
    projectId: 'fir-notifications-api',
    storageBucket: 'fir-notifications-api.firebasestorage.app',
    iosBundleId: 'com.example.carey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLA5oXR27cXVDJeVVdQVnKxxObMxNdoCk',
    appId: '1:364300700938:web:034354f2158245549cbef3',
    messagingSenderId: '364300700938',
    projectId: 'fir-notifications-api',
    authDomain: 'fir-notifications-api.firebaseapp.com',
    storageBucket: 'fir-notifications-api.firebasestorage.app',
    measurementId: 'G-MCWYC2RLY3',
  );
}
