name: Flutter CI/CD

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.27.0
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0' # Use the required Flutter version
      
      - name: Create .env File using GitHub Secrets
        run: |
          echo ${{ secrets.ENV_FILE_CONTENT }} > .env
          echo "Current directory:"
          pwd
          echo -e "\nFiles in current directory:"
          ls
          echo -e "\n.env file content:"
          cat .env

      - name: Clean up the project
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: Carey-apk
          path: build/app/outputs/flutter-apk/app-release.apk
    